//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trial_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AircraftEntry()
        {
            this.EntryAircrafts = new HashSet<EntryAircraft>();
        }
    
        public int AircraftEntryId { get; set; }
        public string ModelNo { get; set; }
        public string ImagePath { get; set; }
        public int NoOfEngine { get; set; }
        public System.DateTime ProductionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryAircraft> EntryAircrafts { get; set; }
    }
}
