//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trial_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryAircraft
    {
        public int EntryAircraftsId { get; set; }
        public int AircraftEntryId { get; set; }
        public int AircraftId { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual AircraftEntry AircraftEntry { get; set; }
    }
}
